/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0        (GUI_ID_USER + 0x0C)
#define ID_BUTTON_0        (GUI_ID_USER + 0x10)
#define ID_HEADER_0        (GUI_ID_USER + 0x11)
#define ID_TEXT_0        (GUI_ID_USER + 0x12)
#define ID_EDIT_0        (GUI_ID_USER + 0x13)
#define ID_EDIT_1        (GUI_ID_USER + 0x14)
#define ID_EDIT_2        (GUI_ID_USER + 0x15)
#define ID_EDIT_3        (GUI_ID_USER + 0x16)
#define ID_TEXT_1        (GUI_ID_USER + 0x17)
#define ID_TEXT_2        (GUI_ID_USER + 0x18)
#define ID_TEXT_3        (GUI_ID_USER + 0x19)
#define ID_TEXT_4        (GUI_ID_USER + 0x1A)
#define ID_BUTTON_1        (GUI_ID_USER + 0x1B)
#define ID_BUTTON_2        (GUI_ID_USER + 0x1C)
#define ID_BUTTON_3        (GUI_ID_USER + 0x1D)
#define ID_BUTTON_4        (GUI_ID_USER + 0x1E)
#define ID_BUTTON_5        (GUI_ID_USER + 0x1F)
#define ID_BUTTON_6        (GUI_ID_USER + 0x20)
#define ID_BUTTON_7        (GUI_ID_USER + 0x21)
#define ID_BUTTON_8        (GUI_ID_USER + 0x22)
#define ID_BUTTON_9        (GUI_ID_USER + 0x23)
#define ID_BUTTON_10        (GUI_ID_USER + 0x24)
#define ID_BUTTON_11        (GUI_ID_USER + 0x25)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "rtc_lost", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "bt_validate", ID_BUTTON_0, 370, 226, 86, 36, 0, 0x0, 0 },
  { HEADER_CreateIndirect, "header_1", ID_HEADER_0, 20, 15, 440, 50, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "txt_1", ID_TEXT_0, 20, 80, 290, 25, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "edit_minute", ID_EDIT_0, 20, 140, 40, 20, 0, 0x18, 0 },
  { EDIT_CreateIndirect, "edit_hour", ID_EDIT_1, 116, 140, 40, 20, 0, 0x3c, 0 },
  { EDIT_CreateIndirect, "edit_year", ID_EDIT_2, 116, 190, 40, 20, 0, 0x0bb8, 0 },
  { EDIT_CreateIndirect, "edit_month", ID_EDIT_3, 20, 190, 40, 20, 0, 0xc, 0 },
  { TEXT_CreateIndirect, "txt_minute", ID_TEXT_1, 65, 140, 50, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "txt_hour", ID_TEXT_2, 161, 140, 50, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "txt_month", ID_TEXT_3, 65, 190, 50, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "txt_year", ID_TEXT_4, 161, 190, 50, 20, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "numpad_7", ID_BUTTON_1, 320, 75, 36, 36, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "numpad_4", ID_BUTTON_2, 320, 125, 36, 36, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "numpad_1", ID_BUTTON_3, 320, 175, 36, 36, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "numpad_8", ID_BUTTON_4, 370, 75, 36, 36, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "numpad_5", ID_BUTTON_5, 370, 125, 36, 36, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "numpad_2", ID_BUTTON_6, 370, 175, 36, 36, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "numpad_0", ID_BUTTON_7, 320, 225, 36, 36, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "numpad_9", ID_BUTTON_8, 420, 75, 36, 36, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "numpad_6", ID_BUTTON_9, 420, 125, 36, 36, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "numpad_3", ID_BUTTON_10, 420, 175, 36, 36, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "bt_skip", ID_BUTTON_11, 50, 230, 80, 30, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'rtc_lost'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    //
    // Initialization of 'bt_validate'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetText(hItem, "Validate");
    BUTTON_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'header_1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_HEADER_0);
    HEADER_AddItem(hItem, 440, "RTC LOST", 14);
    //
    // Initialization of 'txt_1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetText(hItem, "Please provide the current time:");
    TEXT_SetFont(hItem, GUI_FONT_20B_1);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00464646));
    //
    // Initialization of 'edit_minute'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem, "00");
    EDIT_SetFont(hItem, GUI_FONT_13B_1);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, GUI_MAKE_COLOR(0x00464646));
    //
    // Initialization of 'edit_hour'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
    EDIT_SetText(hItem, "00");
    EDIT_SetFont(hItem, GUI_FONT_13B_1);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, GUI_MAKE_COLOR(0x00464646));
    //
    // Initialization of 'edit_year'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
    EDIT_SetText(hItem, "2019");
    EDIT_SetFont(hItem, GUI_FONT_13B_1);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, GUI_MAKE_COLOR(0x00464646));
    //
    // Initialization of 'edit_month'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
    EDIT_SetText(hItem, "01");
    EDIT_SetFont(hItem, GUI_FONT_13B_1);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, GUI_MAKE_COLOR(0x00464646));
    //
    // Initialization of 'txt_minute'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetText(hItem, "minute");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00464646));
    //
    // Initialization of 'txt_hour'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetText(hItem, "hour");
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'txt_month'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetText(hItem, "month");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00464646));
    //
    // Initialization of 'txt_year'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetText(hItem, "year");
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00464646));
    //
    // Initialization of 'numpad_7'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetText(hItem, "7");
    BUTTON_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'numpad_4'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, GUI_FONT_13B_1);
    BUTTON_SetText(hItem, "4");
    //
    // Initialization of 'numpad_1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetText(hItem, "1");
    BUTTON_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'numpad_8'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
    BUTTON_SetFont(hItem, GUI_FONT_13B_1);
    BUTTON_SetText(hItem, "8");
    //
    // Initialization of 'numpad_5'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
    BUTTON_SetText(hItem, "5");
    BUTTON_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'numpad_2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
    BUTTON_SetText(hItem, "2");
    BUTTON_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'numpad_0'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
    BUTTON_SetText(hItem, "0");
    BUTTON_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'numpad_9'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);
    BUTTON_SetFont(hItem, GUI_FONT_13B_1);
    BUTTON_SetText(hItem, "9");
    //
    // Initialization of 'numpad_6'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);
    BUTTON_SetText(hItem, "6");
    BUTTON_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'numpad_3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10);
    BUTTON_SetText(hItem, "3");
    BUTTON_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'bt_skip'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_11);
    BUTTON_SetFont(hItem, GUI_FONT_13B_1);
    BUTTON_SetText(hItem, "Skip");
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'bt_validate'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_HEADER_0: // Notifications sent by 'header_1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_0: // Notifications sent by 'edit_minute'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_1: // Notifications sent by 'edit_hour'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_2: // Notifications sent by 'edit_year'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_3: // Notifications sent by 'edit_month'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'numpad_7'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'numpad_4'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'numpad_1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'numpad_8'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'numpad_5'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_6: // Notifications sent by 'numpad_2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_7: // Notifications sent by 'numpad_0'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_8: // Notifications sent by 'numpad_9'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_9: // Notifications sent by 'numpad_6'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_10: // Notifications sent by 'numpad_3'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_11: // Notifications sent by 'bt_skip'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       Creatertc_lost
*/
WM_HWIN Creatertc_lost(void);
WM_HWIN Creatertc_lost(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
